# Generated by Django 5.1.7 on 2025-03-28 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
        ),
    ]
